# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled0.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1155, 764)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 120, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(220, 40, 721, 581))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 651, 521))
        self.groupBox.setObjectName("groupBox")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        self.menu_5.setObjectName("menu_5")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        self.menu_6.setObjectName("menu_6")
        mainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(mainWindow)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menu_openfile = QtWidgets.QAction(mainWindow)
        self.menu_openfile.setObjectName("menu_openfile")
        self.menu_savefile = QtWidgets.QAction(mainWindow)
        self.menu_savefile.setObjectName("menu_savefile")
        self.menu.addAction(self.menu_openfile)
        self.menu.addAction(self.menu_savefile)
        self.menu_4.addSeparator()
        self.menu_4.addSeparator()
        self.menu_4.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())

        self.retranslateUi(mainWindow)
        self.menu_openfile.triggered.connect(mainWindow.openfile)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("mainWindow", "删除图像"))
        self.groupBox.setTitle(_translate("mainWindow", "图像"))
        self.menu.setTitle(_translate("mainWindow", "文件"))
        self.menu_2.setTitle(_translate("mainWindow", "编辑"))
        self.menu_3.setTitle(_translate("mainWindow", "视图"))
        self.menu_4.setTitle(_translate("mainWindow", "作图"))
        self.menu_5.setTitle(_translate("mainWindow", "工具"))
        self.menu_6.setTitle(_translate("mainWindow", "帮助"))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar"))
        self.menu_openfile.setText(_translate("mainWindow", "打开"))
        self.menu_openfile.setToolTip(_translate("mainWindow", "打开一个数据文件"))
        self.menu_savefile.setText(_translate("mainWindow", "保存"))
