# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 300)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(250, 20, 81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        # self.label = QtWidgets.QLabel(Dialog)
        # self.label.setGeometry(QtCore.QRect(10, 20, 54, 12))
        # self.label.setObjectName("label")
        # self.checkBox = QtWidgets.QCheckBox(Dialog)
        # self.checkBox.setGeometry(QtCore.QRect(110, 20, 71, 16))
        # self.checkBox.setObjectName("checkBox")
        # self.pushButton = QtWidgets.QPushButton(Dialog)
        # self.pushButton.setGeometry(QtCore.QRect(250, 200, 75, 23))
        # self.pushButton.setObjectName("pushButton")


        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        # self.pushButton.clicked.connect(Dialog.specify)
        self.pushButton_2.clicked.connect(Dialog.reverse)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "选择要查看的通道"))
        # self.label.setText(_translate("Dialog", "标签"))
        # self.checkBox.setText(_translate("Dialog", "CheckBox"))
        # self.pushButton.setText(_translate("Dialog", "单独查看"))
        self.pushButton_2.setText(_translate("Dialog", "反选"))
